### ISSUE TITLE
Can't edit boolean values

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-1-cloud-feedback#126]
![image](https://user-images.githubusercontent.com/1567498/37945893-6348d392-3137-11e8-9504-ab963df99717.png)

Even though the value says `true` in the table view, the popup checkbox is unchecked. This makes editing boolean values in the data browser impossbile.

**Comment by chrisrowe** [comment]
Can confirm I lost an hour to this bug.

**Comment by peterschussheim** [comment]
Another report of this bug:

<img width="1048" alt="google chrome028" src="https://user-images.githubusercontent.com/3654683/41993977-f6a3f884-7a1a-11e8-8f5c-7e34e35984be.png">

**Comment by timsuchanek** [comment]
This is fixed by now. If it's still an issue, let us know and we reopen this!
